jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout main branch repository
        uses: actions/checkout@v4
        with:
          ref: main
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/apacheimageproj4:latest
