on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout main branch repository
        uses: actions/checkout@v4
        with:
          ref: main
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            ${{ secrets.DOCKER_USERNAME }}/apacheimageproj4
          tags:
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            latest=true
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
